owner = "milkyskies"
repo = "ghlobes"
project_number = 10
status_field_id = "PVTSSF_lAHOAGCvbs4BQ0_azg-1dkc"
priority_field_id = "PVTSSF_lAHOAGCvbs4BQ0_azg-1dlk"
points_field_id = "PVTF_lAHOAGCvbs4BQ0_azg-2DTc"
